LOG_SYMBOL: ">> " # Символ для вывода отладочной информации
DEBUG: True # Флаг отладки
OUR_USERNAME:     "testcrm994@gmail.com"
OUR_PASSWORD:     "qwerty1@"
SEND_USERNAME:    "testcrm994@gmail.com"
SEND_PASSWORD:    "qwerty1@"
DATABASE_PATH:    "firm.db"
DOCUMENTS_PATH:   "documents\\"
